### ISSUE TITLE
LICENSE information

### ISSUE THREAD

**Issue by goanpeca** [royerlab/arbol#2]
Hi @royerloic, we are in the process of making conda-packages for napari plugins and dependencies. 

I had a question regarding this package. The LICENSE file says it is MIT, but the setup.py metadata says it is BSD.

Also the LICENSE file is not currently being bundled with the tarballs.

I can open a PR to update the packaging once the licensing is clarified.

Thanks :)

**Comment by sofroniewn** [comment]
@royerloic @AhmetCanSolak @JoOkuma any chance you could address this so we can complete the updating of the conda-forge recipe, thanks so much!!!

**Comment by JoOkuma** [comment]
@sofroniewn @goanpeca thanks for pointing this out.
